### ISSUE TITLE
Error on startup when running headless

### ISSUE THREAD

**Issue by baodrate** [pfeiferj/nvim-hurl#1]
These lines in `hurl.lua` (`require`d by `nvim-hurl/init.lua` so you can't really avoid it): https://github.com/pfeiferj/nvim-hurl/blob/e22d346edcb56fe07a96df5f6a83670e4e648d0b/lua/hurl/hurl.lua#L2-L3

cause an error when running neovim headless

```
$ nvim --headless +quit
Error detected while processing command line:
Failed to run `config` for nvim-hurl
$XDG_DATA_HOME/lazy/nvim-hurl/lua/hurl/hurl.lua:2: attempt to index a nil value
# stacktrace:
  - lua/plugins/init.lua:112 _in_ **config**
  - init.lua:188%                                                                                               
```

I can workaround it by conditionally loading nvim-hurl, but it would be nice if we just avoided those functions at loadtime. They're very low impact (~24ms for 10k calls on my machine), so it shouldn't be an issue just calling it when its needed.

**Comment by pfeiferj** [comment]
Pushed up the suggested change. Thanks for reporting!
