### ISSUE TITLE
Run in vertical split?

### ISSUE THREAD

**Issue by alloc33** [pfeiferj/nvim-hurl#2]
Is there any way use vert split as in `rest.nvim`?

**Comment by alloc33** [comment]
Also I noticed that there is no way to close the float with `<C-w c>`. Works only for non-colored float

**Comment by pfeiferj** [comment]
> Is there any way use vert split as in `rest.nvim`?

Currently no, but I'll see if I can get something together. I need to get the treesitter updated for some small changes in the latest version of hurl first, but if that doesn't take long I might be able to get to it tomorrow.

**Comment by pfeiferj** [comment]
> Also I noticed that there is no way to close the float with `<C-w c>`. Works only for non-colored float

The colored float is technically a terminal so ctrl commands have to use the terminal escaped version. I usually just :q it though. It's setup as a scratch buffer so when you close the window with :q the buffer automatically closes as well
