### ISSUE TITLE
Upstream the tree-sitter queries and configuration 

### ISSUE THREAD

**Issue by folliehiyuki** [pfeiferj/nvim-hurl#5]
I personally don't need the `:Hurl` command, as I use another plugin for running tasks.

It would be nice to have the TreeSitter queries and configuration in upstream [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) repo. That way I can just run `:TSInstall hurl` to have nice highlights.

**Comment by folliehiyuki** [comment]
Another user also asked for this (https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1592486197), so it's not just me.

**Comment by pfeiferj** [comment]
> Another user also asked for this (https://github.com/nvim-treesitter/nvim-treesitter/issues/2282#issuecomment-1592486197), so it's not just me.

Yeah, I'm planning on trying to upstream it. Just hasn't hit the top of my priority list yet

**Comment by pfeiferj** [comment]
Closing to consolidate discussion to the issue in the tree-sitter repo: https://github.com/pfeiferj/tree-sitter-hurl/issues/2
